### PR TITLE
Class Objects was add it to validation class

### PR DESCRIPTION
**Pull request by enFaust**

### CODE REVIEW

**Comment by AliaksandrFiodarau3** [comment]
I'm sorry. I add "Fix AccessFilter" to this pull request.

**Comment by vatolinrp** [comment]
it makes no sense replacing `login == null` by `Objects.isNull(login)`. use equals and hashcode of java.util.Object, for example, in your model classes to avoid the implementation of those methods. Here: https://baptiste-wicht.com/posts/2010/04/java-7-the-new-java-util-objects-class.html

**Comment by vatolinrp** [comment]
> I'm sorry. I add "Fix AccessFilter" to this pull request. How can I delete changes from pull request?
1) do a git revert
2) do interactive git rebase where you delete the commit and then do a a git force push
I recommend you to try the second approach

**Comment by vatolinrp** [comment]
please, don't let your PR open for several weeks.

**Pull request closed without merging**
